//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkMultipleResultados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LoggingEntities : DbContext
    {
        public LoggingEntities()
            : base("name=LoggingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logs> Logs { get; set; }
    
        public virtual ObjectResult<EjemploMultipleResultados_Result> EjemploMultipleResultados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EjemploMultipleResultados_Result>("EjemploMultipleResultados");
        }
    }
}
